name: 'Assign Azure AD Group to a Power BI Dataset'
description: 'Assign an Azure AD Group to a Power BI Dataset'
author: 'Mohit Nayar'
branding:
  icon: 'lock'  
  color: 'yellow'
inputs:
  tenant_id:
    description: 'The id of the tenant'
    required: true
  config:
    description: 'The location of the config file which has the permissions information'
    required: true
  files:
    description: 'Files to deploy'
    required: true
  folder:
    description: 'Folder in which the datasets are stored'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
     - ${{ inputs.files }}
     - ${{ inputs.tenant_id }}
     - ${{ inputs.config }}
     - ${{ inputs.folder }}
