name: 'Assign Azure AD Group to a Power BI Dataset'
description: 'Assign an Azure AD Group to a Power BI Dataset'
author: 'Mohit Nayar'
inputs:
  tenant_id:
    description: 'The id of the tenant'
    required: true
  client_id:
    description: 'The id of the SPN'
    required: true
  client_secret:
    description: 'The secret password of the SPN'
    required: true
  config_file:
    description: 'The location of the config file which has the permissions information"
    required: true
  files:
    description: 'Files to deploy'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
     - ${{ inputs.files }}
     - ${{ inputs.client_secret }}
     - ${{ inputs.client_id }}
     - ${{ inputs.tenant_id }}
     - ${{ inputs.config_file }}
